### ISSUE TITLE
Ambiguous moves and unregistered moves

### ISSUE THREAD

**Issue by binarybrain11** [Chewt/chessterm#1]
In this position (1nbqkbnr/1pppppp1/r7/p6p/P6P/R7/1PPPPPP1/1NBQKBNR w Kk - 0 4), white can move two rooks to the square h3. Entering Rah3 reports an ambiguous move, entering R1h3 and R3h3 doesn't move the piece but also doesn't give an error, and Rhh3 does move the piece properly.

**Comment by Chewt** [comment]
It should be fixed with this [commit](https://github.com/Chewt/Chessterm/commit/0f6d1ccbdab64d7f6208e9ecad843b0b5b09ea64)
